joshuaclayton/page_ez

lib/page_ez/page.rb
spec/features/capybara_javascript_spec.rb

What?
=====
This introduces a new method, `#has_{name}_count?`, to allow for
asserting count on a has_many that waits for Capybara to find the
element on the page by using `has_css?` with a defined count argument.

Add method for asserting has_many count while waiting for JS

---

spec/features/capybara_javascript_spec.rb

What?
=====
This test performs a combination of assertions against Capybara's max
wait time in conjunction with current Capybara behavior around when to
wait for an element to be found on the page to verify at an integration
level that we're using the correct underlying Capybara behavior for
assertions.
However, by using this, and based on timing and hardware on CI, this
inherently has test jitter, resulting in periodic failures.
This expands the time windows slightly to be slightly looser in its
assertions while still building confidence we're using the correct
functionality from Capybara.

Expand Capybara wait time blocks to reduce test flakiness

---

lib/page_ez/has_one_result.rb
spec/features/has_one_spec.rb

What?
=====
This fixes a bug where methods weren't delegated property to @result
within the `HasOneResult` class.

Delegate methods to @result without modification

---

lib/page_ez/has_many_result.rb
lib/page_ez/has_one_result.rb
lib/page_ez/page.rb

What?
=====
Rather than call `target.send(...)` and rescue, this adjusts delegation
to follow guidance outlined in https://bugs.ruby-lang.org/issues/16157.
Because the gem only supports Ruby versions >= 3.0, this bypasses the
Ruby 2 support path as it's unnecessary.

Update occurrences of method_missing with improved approach

---

README.md
lib/page_ez.rb
lib/page_ez/configuration.rb
lib/page_ez/null_logger.rb
lib/page_ez/page.rb
spec/lib/page_ez/page_spec.rb
spec/spec_helper.rb
spec/support/matchers/contain_in_order.rb

What?
=====
This introduces basic configuration and the first configuration option:
logging.
This allows the developer to provide a logger to PageEz, which currently
logs out page object definitions, declarations, and method definitions.

Introduce internal logging

---

README.md
spec/features/composition_spec.rb

What?
=====
This updates the README and adds a test as an example for how to compose
PageEz's page objects.

Document page object composition

---

lib/page_ez/page.rb
spec/features/form_spec.rb

What?
=====
This introduces a test and undefines the `select` method (defined in
`Kernel`) to allow for Capybara's `select` method to behave as expected.

Undefine `select` on PageEz::Page so Capybara behavior works

---

README.md
lib/page_ez/page.rb
spec/features/composition_spec.rb

What?
=====
This introduces custom syntax for composing page objects within other
page objects.
```ruby
class ApplicationNav < PageEz::Page
has_one :home_link, "a[data-role='home-link']"
end
class Card < PageEz::Page
has_one :header, "h3"
end
class Dashboard < PageEz::Page
has_many_ordered :metrics, "ul.metrics li" do
has_one :card, Card
end
has_one :primary_nav, ApplicationNav, base_selector: "nav.primary"
end
```
With these three page objects, the following interactions are possible:
```ruby
dashboard_page = Dashboard.new
expect(dashboard_page.metric_at(0).card).to have_header(text: "MRR")
expect(dashboard_page.metric_at(1).card).to have_header(text: "ARR")
expect(dashboard_page).to have_primary_nav
expect(dashboard_page.primary_nav).to have_home_link …
```

Introduce a DSL for composing page objects

---

lib/page_ez.rb
lib/page_ez/page.rb
spec/features/smoke_spec.rb

What?
=====
This introduces a check so duplicate attributes can't be declared for a
given page object by raising a
`PageEz::DuplicateElementDeclarationError`

Raise when duplicate attributes are declared on the same page object

---

.standard.yml

With the existing `ruby_version: 2.6`, the following error is reported:
```
[Lint/Syntax] unexpected token kIN(Using Ruby 2.6 parser; configure
using `TargetRubyVersion` parameter, under `AllCops`) standardrb [36, 7]
```
The gemspec's `required_ruby_version` is set to `>= 3.0.0` so I set the target ruby version to 3.0.

Update target ruby version to 3.0

---

lib/page_ez/page.rb
spec/features/selectors_spec.rb

This commit allows using a Symbol as a selector. The symbol is converted
to a String using `to_s`.
```ruby
class TodoIndex < PageEz::Page
has_one :heading, :h1
end
```
```ruby
todo_index = TodoIndex.new
expect(todo_index).to have_heading(text: "Hello")
```
In cases where a page is utilizing semantic elements, it is convenient
to be able to omit the selector and use the semantic element name as the
selector.
```ruby
class PageWithSidebar < PageEz::Page
has_one :sidebar, "aside"
has_one :main do
has_one :header do
has_one :heading, "h1"
end
has_one :content, "section"
end
end
```

Allow omitting or using a Symbol for selectors

---

lib/page_ez/delegates_to.rb

What?
=====
The previous version of DelegatesTo generated an anonymous module that,
when included, would define methods directly on the object that included
it.
This commit adjusts the behavior slightly to include a new module with
method_missing and respond_to_missing? defined, allowing for the object
including the module to call super to bubble up delegation behavior.

Adjust DelegatesTo to mix in a module rather than define methods directly

---

lib/page_ez/page.rb
spec/features/selectors_spec.rb

What?
=====
This stringifies the selector passed for has_one when the selector is a
symbol.

Support string-ifying selectors when > 1 arg to has_one

---

spec/spec_helper.rb

This commit changes the SimpleCov formatter depending on the environment it is run in. In CI (when `ENV["CI"]` is truthy), it will use the exisitng LcovFormatter. When not in CI, it will use the SimpleFormatter and HTMLFormatter.
This allows for easy coverage viewing when developing locally to see how test changes affect coverage.
If there's already a means to view coverage locally with the LcovFormatter, I'm happy to update this PR to instead include documentation.

Generate an HTML coverage report locally

---

README.md
spec/features/arguments_spec.rb
spec/features/capybara_javascript_spec.rb
spec/features/composition_spec.rb
spec/features/form_spec.rb
spec/features/has_many_ordered_spec.rb
spec/features/has_many_spec.rb
spec/features/has_one_spec.rb
spec/features/macros_with_methods_spec.rb
spec/features/selectors_spec.rb
spec/support/app_generator.rb

What?
=====
Now that patterns have been established within the test suite, we can
safely extract the build_page helper method to a module that's mixed
into RSpec.
This also adjusts behavior to run via a headless browser by using
RSpec's `:js` metadata.

Extract the build_page test helper

---

lib/page_ez/method_generators/has_many_ordered_selector.rb
spec/features/has_many_ordered_spec.rb

What?
=====
This adds the complementary `#has_no_{singular_name}_at?` method to
elements declared as `has_many_ordered` and verifies correct behavior.

Add complementary #has_no_{singular_name}_at? on has_many_ordered

---

lib/page_ez/page.rb
spec/features/smoke_spec.rb

What?
=====
This updates the logic when inheriting from a PageEz::Page class to
reset visitors properly.
Previously, we checked to see if the first ancestor when inheriting was
a `PageEz::Page`. However, this behavior isn't actually correct, as
subclassing occurs in two fashions: from a library usage perspective,
and internally when nesting macros, e.g.
Library usage via traditional inheritance:
```ruby
class ApplicationPage < PageEz::Page
end
class Homepage < ApplicationPage
end
```
Nesting macros:
```ruby
has_one :list, "ul" do
has_many_ordered :items, "li"
end
```
In both cases, the `inherited` hook gets called, but visitors should
only be reset via traditional inheritance and NOT by nesting macros.
This introduces a new class attribute, `nested_macro`, which defaults to
false and is …

Fix bug related to subclassing and macro reuse

---

lib/page_ez/errors.rb
lib/page_ez/method_generators/define_has_many_result_methods.rb
lib/page_ez/method_generators/define_has_one_predicate_methods.rb
lib/page_ez/method_generators/define_has_one_result_methods.rb
spec/features/broken_selector_spec.rb

What?
=====
Nokogiri's CSS::SyntaxError exception does not include the full selector
in its exception, making it hard to understand why exactly a selector
isn't working, especially in tools like PageEz which generates some
selectors dynamically.

Reraise with an improved message on invalid CSS selectors

---

lib/page_ez/page.rb
lib/page_ez/page_visitor.rb
lib/page_ez/visitors/debug_visitor.rb
lib/page_ez/visitors/depth_visitor.rb
lib/page_ez/visitors/macro_pluralization_visitor.rb
lib/page_ez/visitors/matcher_collision_visitor.rb
lib/page_ez/visitors/registered_name_visitor.rb
spec/features/delegation_name_collisions_spec.rb

What?
=====
In addition to macro declaration and defining methods normally,
developers can delegate methods to other instance methods.
This decorates `delegate` to track the "final form" of each method (as
the `to` and `prefix` options impact the resulting method name) and
handle collisions as it does in other instances. Just as in other
instances, the depth of nesting impacts collisions appropriately.

Track name registration for delegated methods

---

README.md
lib/page_ez/method_generators/has_many_ordered_selector.rb
lib/page_ez/method_generators/has_one_composed_class.rb
lib/page_ez/page.rb
spec/features/contains_spec.rb
spec/features/override_container_spec.rb

This introduces `base_selector` and `contains` to allow for a different approach to page object composition.
```rb
class SidebarModal < PageEz::Page
base_selector "div[data-role=sidebar]"
has_one :sidebar_heading, "h2"
has_one :sidebar_contents, "section[data-role=contents]"
end
class PeopleIndex < PageEz::Page
contains SidebarModal
has_many :people_rows, "ul[data-role=people-list] li" do
has_one :name, "span[data-role=person-name]"
has_one :edit_link, "a", text: "Edit"
end
def change_person_name(from:, to:)
people_row_matching(text: from).edit_link.click
within sidebar_contents do
fill_in "Name", with: to
click_on "Save Person"
end
end
end
```

Add ability to define a base selector for a PageEz::Page

---

README.md
lib/page_ez/has_many_result.rb
lib/page_ez/method_generators/define_has_many_result_methods.rb
spec/features/capybara_javascript_spec.rb
spec/features/has_many_spec.rb

What?
=====
This implements methods that were documented (incorrectly, as they
didn't exist yet) for asserting some or no elements matching a has_many.

Implement documented predicate methods for has_many

---

lib/page_ez/page.rb
spec/features/smoke_spec.rb

What?
=====
This addresses a bug with a very specific set of criteria for
reproduction:
* a page object (A) inheriting from PageEz::Page with a macro declaring
a block (nothing needs to be declared in the block)
* a page object (B) inheriting from PageEz::Page that declares a top-level
macro named (X)
* a page object (C) inheriting from (A) that also declares a top-level
macro named (X)
The bug that triggered this failure (a duplicate element declaration
error, which would be on (X) in the example above) was related to a
state change (setting nested_macro to true) when a block is provided to
a macro that wasn't reset after the block was complete.
When a class inherits from PageEz or its subclasses, if it's not nested,
it resets all its visitors. This key behavior wasn't being triggered on …

Fix inheritance bug that doesn't reset state correctly

---

lib/page_ez/page.rb
spec/features/contains_spec.rb

What?
=====
This fixes a bug where base_selector values re-propagate across nested
selectors.
Resolves #51

Fix base_selector propagation through the page hierarchy
